branches:
  - name: "master"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: scripts/publish.sh
  - - "@semantic-release/github"
    - assets:
      - anotherchart-${nextRelease.version}.tgz
  - - "@semantic-release/changelog"
    - assets:
      - CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - anotherchart/Chart.yaml
