branches:
  - name: "master"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        scripts/publish.sh ${nextRelease.version}
  - - "@semantic-release/github"
    - assets:
      - anotherchart-*.tgz
  - - "@semantic-release/changelog"
    - assets:
      - CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - anotherchart/Chart.yaml
      - index.yaml
