branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - master
  - next
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        sed -i "s/^version '.*'/version '${nextRelease.version}'/g" cookbooks/releasecook/metadata.rb
  - "@semantic-release/github"
  - - "@semantic-release/changelog"
    - changelogFile: cookbooks/releasecook/CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
      - cookbooks/releasecook/CHANGELOG.md
      - cookbooks/releasecook/metadata.rb
