branches:
  - name: "master"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        wget https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz && \
        tar -zxvf helm-v3.2.1-linux-amd64.tar.gz && \
        sed -i "s/version: .*/version: ${nextRelease.version}/g" anotherchart/Chart.yaml && \
        linux-amd64/helm package --version ${nextRelease.version} anotherchart/. && \
        linux-amd64/helm repo index --url https://gopisaba.github.io/test-release/ --merge index.yaml anotherchart/.
  - - "@semantic-release/github"
    - assets:
      - anotherchart-*.tgz
  - - "@semantic-release/changelog"
    - assets:
      - CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - anotherchart/Chart.yaml
      - index.yaml
