plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/github"
  - "@semantic-release/release-notes-generator"
branches:
  - "master"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "alpha"
    prerelease: "alpha"
